python ./star/train_adapters.py --do_train \
    --max_query_length 24 \
    --max_doc_length 120 \
    --workers 4 \
    --batch_size 512 \
    --preprocess_dir ../dataset/bert \
    --output_dir ./data/adapters/model \
    --logging_dir ./data/adapters/log \
    --optimizer_str lamb \
    --learning_rate 1e-4 \
    --fp16 \
    --train_adapter \
    --overwrite_output_dir