python ./star/train_warmup.py --do_train \
    --max_query_length 24 \
    --max_doc_length 120 \
    --workers 4 \
    --batch_size 1024 \
    --preprocess_dir ../dataset/bert \
    --output_dir ./data/warmup_exp/model \
    --logging_dir ./data/warmup_exp/log \
    --optimizer_str lamb \
    --learning_rate 1e-4 \
    --fp16 \
    --overwrite_output_dir